# """add is_verified to users

# Revision ID: 154c713cd0fd
# Revises: 
# Create Date: 2026-08-01 23:34:54.964659

# """
# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa
# from sqlalchemy.dialects import postgresql

# # revision identifiers, used by Alembic.
# revision: str = '154c713cd0fd'
# down_revision: Union[str, None] = None
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('expenses')
#     op.drop_table('reports')
#     op.drop_table('savingsgoals')
#     op.drop_table('income')
#     op.drop_table('notifications')
#     op.drop_table('budgets')
#     op.alter_column('profiles', 'user_id',
#                existing_type=sa.INTEGER(),
#                nullable=True)
#     op.alter_column('profiles', 'full_name',
#                existing_type=sa.VARCHAR(length=150),
#                nullable=True)
#     op.alter_column('profiles', 'monthly_income',
#                existing_type=sa.NUMERIC(precision=12, scale=2),
#                type_=sa.Float(),
#                existing_nullable=True)
#     op.alter_column('profiles', 'financial_preferences',
#                existing_type=sa.TEXT(),
#                type_=sa.String(),
#                existing_nullable=True)
#     op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
#     op.create_unique_constraint(None, 'profiles', ['user_id'])
#     op.drop_constraint(op.f('fk_profile_user'), 'profiles', type_='foreignkey')
#     op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'])
#     op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
#     op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
#     op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
#     op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
#     op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
#     op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_index(op.f('ix_users_username'), table_name='users')
#     op.drop_index(op.f('ix_users_id'), table_name='users')
#     op.drop_index(op.f('ix_users_email'), table_name='users')
#     op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
#     op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
#     op.drop_column('users', 'is_verified')
#     op.drop_constraint(None, 'profiles', type_='foreignkey')
#     op.create_foreign_key(op.f('fk_profile_user'), 'profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
#     op.drop_constraint(None, 'profiles', type_='unique')
#     op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
#     op.alter_column('profiles', 'financial_preferences',
#                existing_type=sa.String(),
#                type_=sa.TEXT(),
#                existing_nullable=True)
#     op.alter_column('profiles', 'monthly_income',
#                existing_type=sa.Float(),
#                type_=sa.NUMERIC(precision=12, scale=2),
#                existing_nullable=True)
#     op.alter_column('profiles', 'full_name',
#                existing_type=sa.VARCHAR(length=150),
#                nullable=False)
#     op.alter_column('profiles', 'user_id',
#                existing_type=sa.INTEGER(),
#                nullable=False)
#     op.create_table('budgets',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
#     sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
#     sa.Column('monthly_limit', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
#     sa.CheckConstraint('monthly_limit >= 0::numeric', name=op.f('budgets_monthly_limit_check')),
#     sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_budget_user'), ondelete='CASCADE'),
#     sa.PrimaryKeyConstraint('id', name=op.f('budgets_pkey'))
#     )
#     op.create_table('notifications',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
#     sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
#     sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'Unread'::character varying"), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_user'), ondelete='CASCADE'),
#     sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
#     )
#     op.create_table('income',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
#     sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
#     sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
#     sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
#     sa.CheckConstraint('amount >= 0::numeric', name=op.f('income_amount_check')),
#     sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_income_user'), ondelete='CASCADE'),
#     sa.PrimaryKeyConstraint('id', name=op.f('income_pkey'))
#     )
#     op.create_table('savingsgoals',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
#     sa.Column('goal_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
#     sa.Column('target_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
#     sa.Column('current_amount', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
#     sa.CheckConstraint('current_amount >= 0::numeric', name=op.f('savingsgoals_current_amount_check')),
#     sa.CheckConstraint('target_amount >= 0::numeric', name=op.f('savingsgoals_target_amount_check')),
#     sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_goal_user'), ondelete='CASCADE'),
#     sa.PrimaryKeyConstraint('id', name=op.f('savingsgoals_pkey'))
#     )
#     op.create_table('reports',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
#     sa.Column('report_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
#     sa.Column('generated_date', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_report_user'), ondelete='CASCADE'),
#     sa.PrimaryKeyConstraint('id', name=op.f('reports_pkey'))
#     )
#     op.create_table('expenses',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
#     sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
#     sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
#     sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
#     sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
#     sa.CheckConstraint('amount >= 0::numeric', name=op.f('expenses_amount_check')),
#     sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_expense_user'), ondelete='CASCADE'),
#     sa.PrimaryKeyConstraint('id', name=op.f('expenses_pkey'))
#     )
#     # ### end Alembic commands ###


"""add is_verified to users

Revision ID: 154c713cd0fd
Revises: 
Create Date: 2026-08-01 23:34:54.964659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '154c713cd0fd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'users',
        sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.false())
    )


def downgrade() -> None:
    op.drop_column('users', 'is_verified')