"""add savings goals and notifications

Revision ID: 1c2bb8b4c11f
Revises: 1e0e56519622
Create Date: 2026-08-11 21:10:25.163382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c2bb8b4c11f'
down_revision: Union[str, None] = '1e0e56519622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
