"""add accounts table and account_id to income and expense

Revision ID: 1e0e56519622
Revises: 83a46aac268f
Create Date: 2026-08-06 23:04:51.231088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e0e56519622'
down_revision: Union[str, None] = '83a46aac268f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.drop_table('notifications')
    op.drop_table('savingsgoals')
    op.drop_table('reports')
    op.alter_column('budgets', 'month_year',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)
    op.create_index(op.f('ix_budgets_id'), 'budgets', ['id'], unique=False)
    op.add_column('expenses', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_foreign_key(None, 'expenses', 'accounts', ['account_id'], ['id'], ondelete='SET NULL')
    op.add_column('income', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_income_id'), 'income', ['id'], unique=False)
    op.create_foreign_key(None, 'income', 'accounts', ['account_id'], ['id'], ondelete='SET NULL')
    op.alter_column('profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('profiles', 'full_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('profiles', 'monthly_income',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('profiles', 'financial_preferences',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_unique_constraint(None, 'profiles', ['user_id'])
    op.drop_constraint(op.f('fk_profile_user'), 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_profile_user'), 'profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'profiles', type_='unique')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.alter_column('profiles', 'financial_preferences',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('profiles', 'monthly_income',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('profiles', 'full_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'income', type_='foreignkey')
    op.drop_index(op.f('ix_income_id'), table_name='income')
    op.drop_column('income', 'account_id')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_column('expenses', 'account_id')
    op.drop_index(op.f('ix_budgets_id'), table_name='budgets')
    op.alter_column('budgets', 'month_year',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)
    op.create_table('reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('report_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('generated_date', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_report_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('reports_pkey'))
    )
    op.create_table('savingsgoals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('goal_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('target_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('current_amount', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.CheckConstraint('current_amount >= 0::numeric', name=op.f('savingsgoals_current_amount_check')),
    sa.CheckConstraint('target_amount >= 0::numeric', name=op.f('savingsgoals_target_amount_check')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_goal_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('savingsgoals_pkey'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'Unread'::character varying"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
