"""add icon to savings_goal

Revision ID: a3dadb3045dd
Revises: f107d57058c2
Create Date: 2026-08-22 15:35:51.585267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3dadb3045dd'
down_revision: Union[str, None] = 'f107d57058c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('savings_goals', sa.Column('icon', sa.String(length=30), nullable=False))
    op.add_column('savings_goals', sa.Column('icon', sa.String(length=30), nullable=False, server_default='target'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('savings_goals', 'icon')
    # ### end Alembic commands ###
